### ISSUE TITLE
Build failure: Class java/util/UUID could not be instrumented.

### ISSUE THREAD

**Issue by wkiri** [AccelerationNet/access2csv#20]
I updated the Maven version from 1.6 to 1.7 (as in PR #18 ), but I still can't complete the installation from the latest source (see below).  I'm running MacOSX 10.15.4 and Java 17.0.1.  I wonder if you have any thoughts?

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
	at org.jacoco.agent.rt.internal_773e439.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:139)
	at org.jacoco.agent.rt.internal_773e439.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:100)
	at org.jacoco.agent.rt.internal_773e439.PreMain.createRuntime(PreMain.java:55)
	at org.jacoco.agent.rt.internal_773e439.PreMain.premain(PreMain.java:47)
	... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
	at java.base/java.lang.Class.getField(Class.java:2117)
	at org.jacoco.agent.rt.internal_773e439.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:137)
	... 9 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
/bin/sh: line 1: 71045 Abort trap: 6           /usr/local/Cellar/openjdk/17.0.1_1/libexec/openjdk.jdk/Contents/Home/bin/java -javaagent:.m2/repository/org/jacoco/org.jacoco.agent/0.7.4.201502262128/org.jacoco.agent-0.7.4.201502262128-runtime.jar=destfile=access2csv/target/jacoco.exec -jar access2csv/target/surefire/surefirebooter8339662964889775121.jar access2csv/target/surefire/surefire4240032854075140718tmp access2csv/target/surefire/surefire_02164987154270898057tmp

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.949 s
[INFO] Finished at: 2022-01-14T18:17:02-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project access2csv: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd access2csv && /usr/local/Cellar/openjdk/17.0.1_1/libexec/openjdk.jdk/Contents/Home/bin/java -javaagent:.m2/repository/org/jacoco/org.jacoco.agent/0.7.4.201502262128/org.jacoco.agent-0.7.4.201502262128-runtime.jar=destfile=access2csv/target/jacoco.exec -jar access2csv/target/surefire/surefirebooter8339662964889775121.jar access2csv/target/surefire/surefire4240032854075140718tmp access2csv/target/surefire/surefire_02164987154270898057tmp
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by bobbysmith007** [comment]
I don't use this software, nor Mac/OSX - so unfortunately I do not

**Comment by noodlor** [comment]
Having this issue on Ubuntu today.

**Comment by lgallindo** [comment]
I have this issue on both Debian and Windows 10.

Running with ```mvn clean install -DskipTests``` gets me a binary, but the final executable is not responding.
